version: '3.0'
services:
  nginx:
    build:
      context: nginx/
    volumes:
      - type: bind
        source: ./apps
        target: /usr/share/nginx/html/
    ports:
      - "80:80"
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: CC
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 512M
    ports:
      - "5432:5432"

